// HOME PAGE BUTTONS
export const RENTAL_BUTTON = 'RENTAL_BUTTON';
export const SERVICE_BUTTON = 'SERVICE_BUTTON';
export const MEMBERSHIPS_BUTTON = 'MEMBERSHIPS_BUTTON';

// EQUIPMENT CATEGORY BUTTONS
export const CAMERA_BUTTON = 'CAMERA_BUTTON';
export const LIGHTING_BUTTON = 'LIGHTING_BUTTON';
export const AUDIO_BUTTON = 'AUDIO_BUTTON';